### ISSUE TITLE
Bill Of Materials and Component Placement List?

### ISSUE THREAD

**Issue by juanlufont** [Tecsmith/flying-horse-foot#1]
First, thanks to @vinorodrigues for your effort recreating the "Flying Horse Foot" and sharing it (and thanks to the people that made it possible in first place). Probably an GitHub issue is not the optimal way to discuss this, but it's the only way I have found to contact you.

I am a person with limited soldering tools and skills, so I was checking the PCB assembly services from JLCPCB. In addition to the Gerber files, they request the BOM (Bill of Materials) and CPL (Component Placement List) before giving an estimate of the assembly cost. My goal is to get a couple of microcontroller replacements (I have 2 Filco TKL) and not have to worry about the more complicated SMD components.

My knowledge about PCB design is almost non-existeng, but taking a look at the Gerber files and using the component list from your README.md I managed to put together  a draft for the BOM and CPL files, in the end they are just CSV files with a couple of columns.

I was wondering if your original Eagle files have already the required info to generate a BOM file (I guess the CPL is no problem) and if you consider it useful (and adequate) to include them in the repository. If the BOM file needs some extra work I can try to put together one and create a PR.

**Comment by vinorodrigues** [comment]
The Eagle files have all the info you need to do this ... but there are two dimensions to building assembly boards for JLCPCB - 

1. Generating the BOM and CPL files - as you mentioned ... this is relatively easy.  See this video for help: https://www.youtube.com/watch?v=y3GviDr0o1s 

2. When initially designing the board attempt to stick as much as possible to items available in the LCSC (https://jlcpcb.com/parts) ... this part I never did.  Even though I myself had the boards built by JLC I always intended to do the soldering myself (because a few of the components like the magnetic switch and CPU, just to name a few, are "extended" - and this would have added significant cost to the build).

For me, I only had 1 keyboard, but had 5 pcb's made (moq), and fully built 2 - one of which I installed and is fully working on both QMK and VIA.

And herein is the conundrum - I could go through all the effort to build the BOM and CPL's myself and publish them here, but, as my are already built I have no enthusiasm to do so.

Alas, you're welcome to try following the video link above and try it yourself.  If you get stuck then reach out to me via email ....  get that from the email link on tecsmith.com.au

**Comment by juanlufont** [comment]
Thanks a lot for the comments and info!

I will play a bit with the Eagle files and try to generate the BOM and CPL files covering the non-extended components.
